### ISSUE TITLE
タスク確認

### ISSUE THREAD

**Issue by y-ohgi** [mikanyo-guruto/NewsReader#4]
今日学校あったんすね、僕は実家で遊んでいます。
タスクを振ってもらえればやりますが、なければないでやぶさかではない

**Comment by mikanyo-guruto** [comment]
お疲れ様です。
自分は正月忙しかったので、今日は状況把握してちょっと進めばいいかなと思っていましたので。
取り敢えず大丈夫です。わざわざありがとうございます。
